import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DragAndDropProvider from "@/_libs/services/DragAndDropProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gray-100 w-full h-full">
          <DragAndDropProvider>{children}</DragAndDropProvider>
        </main>
      </body>
    </html>
  );
}
